repository: ajnavarro/ajnavarro.github.io
favicon: images/favicon.ico

# Personal info
name: Antonio Navarro
title: Senior Engineer
email: resume@ajnavarro.com
website: ajnavarro.com


# Social links
twitter_username: ajnperez
github_username:  ajnavarro
linkedin_username: ajnavarro

# About Section
about_title: About Me
about_content: | # this will include new lines to allow paragraphs
    Software Engineer specializing in decentralized systems and large-scale data processing.
    My expertise lies in applying principles from <mark>Big Data</mark>, including complex data pipelines and distributed computing.
    I want to build the next generation of robust and scalable <mark>web3</mark> applications.
    I specialize in solving complex data challenges to build fast and reliable web3 systems.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: About Me
more_content: |
    I enjoy building things, from programming microcontrollers for quadruped robots and MIDI devices to creating music with synthesizers.
    I'm also an avid hiker and a former competitive roller hockey player.

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme@v1.8.9

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
