# Site
repository: ajnavarro/ajnavarro.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Antonio Navarro
title: Senior Engineer
email: resume@ajnavarro.com
website: ajnavarro.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: ajnperez
github_username:  ajnavarro
linkedin_username: ajnavarro
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_profile_image: images/profile.jpg
about_title: About Me
about_content: |
    Software Engineer specializing in decentralized systems and large-scale data processing.
    My expertise lies in applying principles from <mark>Big Data</mark>, including complex data pipelines and distributed computing.
    I want to build the next generation of robust and scalable <mark>web3</mark> applications using the <mark>Go</mark> language.
    I specialize in solving complex data challenges to build fast and reliable web3 systems.

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: All in Bits
        link: gno.land
        sub_title: Senior Engineer, Core Team
        caption: March 2023 - Present
        quote: >
          Gno.land is a platform for writing smart contracts in Gnolang (Gno), an interpreted version of Go.
        description: | 
            - Refactored the <mark>blockchain indexer</mark>, making it run <mark>10x faster</mark> and turning it into a key part of the Gno.land block explorer.
            - Built and released a new <mark>GraphQL API</mark> used by over <mark>80% of the platform's partners</mark>.
            - Improved the GraphQL API by adding a new filtering system based on user requests, allowing for complex, <mark>SQL-like searches</mark>.
            - Set up an automated system (<mark>CI</mark>) to test performance and create charts, which helped find and fix slowdowns in the code.
            - Helped create and build gno-by-example.com, a complete guide that became a key resource for new developers.
      - layout: left
        title: Protocol Labs
        link: protocol.ai
        sub_title: Senior Engineer, IPFS Stewards Team
        caption: Apr 2022 - Feb 2023
        quote: >
          Kubo (go-ipfs) is the earliest and most widely used implementation of IPFS.
        description: | 
            - General maintenance of the <mark>IPFS</mark> Go ecosystem, adding new features into the canonical implementation: <mark>Kubo</mark>.
            - Improving the Kubo <mark>Routing system</mark>, allowing composition of routing implementations depending on the use case.
            - <mark>Resource Manager</mark> implementation and UX tweaking and bug fixing, simplifying the user-facing API.
      - layout: left
        title: Molecula Corp.
        link: molecula.com
        sub_title: Senior Engineer, Core Team
        caption: Sep 2020 - Jun 2021
        quote: >
          Pilosa is an open-source, distributed bitmap index that dramatically accelerates continuous analysis across multiple, massive data sets.
        description: | 
            - Refactored cluster management logic from Gossip protocol to <mark>Raft</mark>, using <mark>etcd</mark> for <mark>distributed consensus</mark>.
            - Designed and prototyped a new generic <mark>SQL interface</mark> and new data storage formats.
      - layout: left
        title: Source{d}
        link: sourced.tech
        sub_title: Lead Engineer Data Processing Team
        caption: Sep 2016 - Nov 2019
        quote: >
          Source{d} looks to build the first AI that understands and writes code.
        description: | 
            - Development of <mark>low-level git</mark> functionality (LRU object cache, delta objects generation).
            - Managed and coordinated a <mark>5-person team</mark>.
            - Developed a new <mark>SparkSQL</mark> data source for gitbase, supporting expression <mark>pushdown</mark>.
            - Managed open source projects like <mark>go-git</mark>, <mark>go-mysql-server</mark>, and <mark>gitbase</mark>.
      - layout: left
        title: StratioBD
        link: stratio.com
        sub_title: Big Data Engineer
        caption: Feb 2014 - Sep 2016
        description: | 
            - Architected and developed large-scale, <mark>real-time data processing</mark> platforms and a <mark>Spark-based data lake</mark> for <mark>Santander Bank</mark>.
      - layout: left
        title: TECHNOactivity
        link: www.technoactivity.com
        sub_title: Senior Software Engineer
        caption: Dec 2012 - Feb 2014
        description: | 
            - Architected a highly available, cloud-based <mark>REST API</mark> for a <mark>mobile payments</mark> solution licensed by the <mark>Central Bank of Spain</mark>.
      - layout: left
        title: Antena 3
        link: www.antena3.com
        sub_title: Software Engineer
        caption: Oct 2011 - Dec 2012
        description: | 
            - Developed full-stack media applications for major broadcasters across <mark>Android</mark>, <mark>Smart TV</mark>, and web platforms.
      - layout: left
        title: AT Sistemas
        link: atsistemas.com
        sub_title: Software Engineer
        caption: Sep 2009 - Oct 2011
        description: | 
            - Developed full-stack <mark>Java</mark> enterprise applications for clients such as <mark>Mutua Madrileña</mark> and Franquicias Plus.
      - layout: left
        title: Sadiel Desarrollo de Sistemas
        link: ayesa.com
        sub_title: Junior Software Engineer
        caption: Jan 2009 - Sep 2009
        description: | 
            - Developed enterprise applications using <mark>Java EE</mark> for public sector clients.

  - title: Projects
    layout: list 
    content:
      - layout: left
        title: distribyted
        link: github.com/distribyted/distribyted
        # link_text: Project Website
        quote: >
          A torrent client that exposes files as a standard filesystem for on-demand downloading.
        description: |
            - Architected and developed the entire system from the ground up as a personal project.
            - Implemented a <mark>FUSE</mark> layer to present torrents as a filesystem for seamless integration with other apps.
      - layout: left
        title: Kubo
        link: github.com/ipfs/kubo
        quote: >
          The primary and most widely-used Go implementation of the Interplanetary Filesystem (IPFS).
        description: |
            - Kubo is the reference implementation for the <mark>Web3</mark> standard for content-addressing, providing the core network service, CLI, and HTTP gateway for the <mark>IPFS</mark> network.
      - layout: left
        title: go-mysql-server
        link: github.com/src-d/go-mysql-server
        quote: >
          A generic and extensible SQL engine in Go that parses and optimizes queries for custom data sources.
        description: |
            - Contributed to the core <mark>SQL engine</mark>, focusing on query parsing, optimization, and the interface for custom data sources.
            - Helped establish the project, now heavily used and maintained by the Dolt team.
      - layout: left
        title: go-git
        link: github.com/go-git/go-git
        quote: >
          A highly extensible, pure Go implementation of Git used by major tech companies like Keybase.
        description: |
            - As a <mark>core maintainer</mark>, I implemented major features, including the first version of the packfile writer with delta selection.
            - Drove significant <mark>performance improvements</mark> through low-level profiling and heavy optimization.
      - layout: left
        title: gitbase
        link: github.com/src-d/gitbase
        quote: >
          A SQL database interface, using the MySQL wire protocol, to query Git repositories.
        description: |
            - <mark>Co-created the project</mark> during a company <mark>hackathon</mark>; it later evolved into a main pillar of the company's technology.
            - Designed and implemented core features to query Git history and code ASTs using <mark>SQL</mark>.
      - layout: left
        title: SAP Hana Vora
        link: github.com/SAP/HANAVora-Extensions
        quote: >
          A distributed SQL query layer based on Apache Spark for SAP's in-memory database.
        description: |
            - Collaborated directly with the SAP team to design and build the core <mark>Spark-based SQL</mark> layer for the product.

  - title: Education
    layout: list
    content:
      - layout: top-middle
        title: IES Mar de Cádiz
        caption: 2006 - 2008
        sub_title: Desarrollo de Aplicaciones Informáticas

  - title: More About Me
    layout: text
    content: | 
     I enjoy building things, from programming microcontrollers for quadruped robots and MIDI devices to creating music with synthesizers.
     I'm also an avid hiker and a former competitive roller hockey player.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]